### ISSUE TITLE
Not able to run the agent for .net core

### ISSUE THREAD

**Issue by hemant-learningforever** [SkyAPM/SkyAPM-dotnet#173]
- Why do you submit this issue?
I am using the aspnet core agent for auto instrumentation and not able to get going without grpc server.
 
___
### Question
I have created one sample app and done the setup like below

dotnet new mvc -n sampleapp
cd sampleapp
dotnet add package SkyAPM.Agent.AspNetCore
set ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
set SKYWALKING__SERVICENAME=sample_app
dotnet run

Post this when i hit my app in skyapm logs i can see there is an issue with grpc server.

2019-03-26 19:31:38.324 +05:30 [TestMyWebAPICore] [Information] SkyApm.InstrumentStartup : Started SkyAPM .NET Core Agent.
2019-03-26 19:31:48.478 +05:30 [TestMyWebAPICore] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()

Can i skip the grpc server and just get all traces in skyapm.log?
Can you please explain the role of grpc server?

Thanks,
Hemant,

**Comment by caozhiyuan** [comment]
Can i skip the grpc server and just get all traces in skyapm.log?
if you change some code can, but  just log not a apm.
Can you please explain the role of grpc server?
there : https://github.com/apache/incubator-skywalking , it has well server support and admin and java-agent

**Comment by hemant-learningforever** [comment]
@caozhiyuan  Information was useful. Thanks.
