### ISSUE TITLE
System.IO.IOException: Error loading native library "/app/runtimes/linux/native/libgrpc_csh arp_ext.x64.so"

### ISSUE THREAD

**Issue by Seanwong933** [SkyAPM/SkyAPM-dotnet#207]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
I was starting skywalking agent on an alpine linux docker container failed with thie error:
```bash
info: SkyWalking.AspNetCore.SkyWalkingHostedService[0]
      SkyWalking Agent starting...
fail: SkyWalking.AspNetCore.SkyWalkingHostedService[0]
      SkyWalking Agent start fail.
System.IO.IOException: Error loading native library "/app/runtimes/linux/native/libgrpc_csh
arp_ext.x64.so"
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 
options)
   at SkyWalking.Remote.GrpcChannelBuilder.Build()
   at SkyWalking.Remote.GrpcConnection..ctor(String server, String rootCertificatePath, Str
ing token)
   at SkyWalking.Remote.GrpcConnectionManager.ConnectAsync(TimeSpan timeout)
   at SkyWalking.AspNetCore.SkyWalkingHostedService.StartAsync(CancellationToken cancellati
onToken)
Hosting environment: Production
Content root path: /app
Now listening on: http://0.0.0.0:8088
Application started. Press Ctrl+C to shut down.
```
There's a related [issue](https://github.com/grpc/grpc/issues/15605) says I should Install `libc-compact`.
```
apk update && apk add libc6-compat
```
But that's not work for me.

How to solve this? Any idea or information would be appreciate, thanks.

**Comment by caozhiyuan** [comment]
check you publish dir this file exist ：runtimes/linux/native/libgrpc_csarp_ext.x64.so ，if exist , check has right prerequisites to access it .

@Seanwong933

**Comment by Seanwong933** [comment]
@caozhiyuan Seems nothing special there, thanks for help.
I switched my base image from alpine to bionic solved this issue.
