### ISSUE TITLE
Please delete builder.AddSkyWalkingDefaultConfig();

### ISSUE THREAD

**Issue by 786744873** [SkyAPM/SkyAPM-dotnet#223]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ √] Feature or performance improvement

___
### Requirement or improvement
Please look as this code in source code ,The convention that you use strong Json files make me so difficult to use Apollo to specify configuration files.My `Configuration` will be override by this code.I suggesd delete `builder.AddSkyWalkingDefaultConfig();` and can use other config json file named by users

___
### Example
![image](https://user-images.githubusercontent.com/24601648/61880642-d98d1d00-af27-11e9-8541-f81a1f3a8639.png)
I user config json file in local or remote address,but will override by `builder.AddSkyWalkingDefaultConfig();``Shutdown connection[localhost:11800].`

![image](https://user-images.githubusercontent.com/24601648/61880864-3d174a80-af28-11e9-8e2f-ce266aa7e61f.png)

ErrorLog:

> 2019-07-25 21:44:21.502 +08:00 [My_Service] [Information] SkyApm.InstrumentStartup : Initializing ...
2019-07-25 21:44:21.535 +08:00 [My_Service] [Information] SkyApm.Service.RegisterService : Loaded instrument service [SkyApm.Service.RegisterService].
2019-07-25 21:44:21.535 +08:00 [My_Service] [Information] SkyApm.Service.PingService : Loaded instrument service [SkyApm.Service.PingService].
2019-07-25 21:44:21.535 +08:00 [My_Service] [Information] SkyApm.Service.ServiceDiscoveryV5Service : Loaded instrument service [SkyApm.Service.ServiceDiscoveryV5Service].
2019-07-25 21:44:21.535 +08:00 [My_Service] [Information] SkyApm.Service.SegmentReportService : Loaded instrument service [SkyApm.Service.SegmentReportService].
2019-07-25 21:44:21.537 +08:00 [My_Service] [Information] SkyApm.Service.CLRStatsService : Loaded instrument service [SkyApm.Service.CLRStatsService].
2019-07-25 21:44:21.538 +08:00 [My_Service] [Information] SkyApm.Sampling.SimpleCountSamplingInterceptor : Loaded instrument service [SkyApm.Sampling.SimpleCountSamplingInterceptor].
2019-07-25 21:44:21.538 +08:00 [My_Service] [Information] SkyApm.Transport.Grpc.V6.ConnectService : Loaded instrument service [SkyApm.Transport.Grpc.V6.ConnectService].
2019-07-25 21:44:21.576 +08:00 [My_Service] [Information] SkyApm.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [HttpHandlerDiagnosticListener].
2019-07-25 21:44:21.578 +08:00 [My_Service] [Information] SkyApm.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [Microsoft.AspNetCore].
2019-07-25 21:44:21.578 +08:00 [My_Service] [Information] SkyApm.InstrumentStartup : Started SkyAPM .NET Core Agent.
2019-07-25 21:44:31.661 +08:00 [My_Service] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
2019-07-25 21:44:36.576 +08:00 [My_Service] [Information] SkyApm.Transport.Grpc.ConnectionManager : Shutdown connection[localhost:11800].
2019-07-25 21:44:46.595 +08:00 [My_Service] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()

**Comment by liuhaoyang** [comment]
Maybe this discussion https://github.com/SkyAPM/SkyAPM-dotnet/issues/98 can help you.

**Comment by ElderJames** [comment]
That is, you can implement an IAdditionalConfigurationSource to fit your own configuration source.
