### ISSUE TITLE
希望SkyApm能提供比较友好的docker部署体验.

### ISSUE THREAD

**Issue by jiahengaa** [SkyAPM/SkyAPM-dotnet#232]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
* [x] Feature or performance improvement

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
可以提供比较友好的的docker部署方式吗?我在ubuntu18.04中使用docker部署碰到很多问题.
1.以下是我的dockerfile
``` dockerfile
FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /
RUN dotnet tool install -g SkyWalking.DotNet.CLI
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet skywalking install

ENV PATH="$PATH:/usr/local/share/dotnet"
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore
ENV DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore/shared/Microsoft.NETCore.App/2.1.0
# COPY --from=build /usr/local/share/dotnet/store /usr/share/dotnet/store
# COPY --from=build /usr/local/share/dotnet/store /usr/local/share/dotnet/store
# COPY --from=build /usr/local/share/dotnet/x64 /usr/local/share/dotnet/x64
# COPY --from=build /usr/local/share/dotnet/store/x64/netcoreapp2.1 /app/
COPY bin/Debug/netcoreapp2.2/publish /app/
WORKDIR /app
ENTRYPOINT ["dotnet", "Ids4CenterApp.dll"]
```
dockerfile里只用了一个构建阶段,因此没有做拷贝SkyWalking.Agent.AspNetCore的动作.
2. 启动容器后报错如下:
``` shell
Hosting environment: Production
Content root path: /app
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
      Hosting startup assembly exception
System.InvalidOperationException: Startup assembly SkyWalking.Agent.AspNetCore failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SkyWalking.Agent.AspNetCore, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
Now listening on: http://10.1.30.251:12345
Application started. Press Ctrl+C to shut down.
```
此部分的报错信息和使用[https://github.com/SkyAPM/SkyAPM-dotnet/issues/95](url)中的推荐dockerfile配置
```dockerfile
FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
RUN dotnet tool install -g SkyWalking.DotNet.CLI
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet skywalking install
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /

FROM base AS final
ENV PATH="$PATH:/usr/local/share/dotnet/store"
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore
ENV DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore
COPY --from=build /usr/local/share/dotnet/store /usr/share/dotnet/store
COPY --from=build /usr/local/share/dotnet/x64 /usr/local/share/dotnet/x64
```
输出的报错信息一致.
3. 环境问题排查
3.1 首先attch到已启动的容器中,确认skywalking 是否已正确安装,结果如下,证明已安装
``` shell
root@gc:/# ls
app  bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@gc:/# cd usr/local/share/
root@gc:/usr/local/share# ls
ca-certificates  dotnet  man
root@gc:/usr/local/share# cd dotnet/
root@gc:/usr/local/share/dotnet# ls
store  x64
root@gc:/usr/local/share/dotnet# ls store/x64/netcoreapp2.1/
artifact.xml                                             microsoft.net.http.headers/
google.protobuf/                                         mysqlconnector/
grpc.core/                                               newtonsoft.json/
microsoft.aspnetcore.hosting.abstractions/               npgsql/
microsoft.aspnetcore.hosting.server.abstractions/        npgsql.entityframeworkcore.postgresql/
microsoft.aspnetcore.http.abstractions/                  pomelo.entityframeworkcore.mysql/
microsoft.aspnetcore.http.extensions/                    pomelo.jsonobject/
microsoft.aspnetcore.http.features/                      remotion.linq/
microsoft.aspnetcore.mvc.abstractions/                   serilog/
microsoft.aspnetcore.routing.abstractions/               serilog.extensions.logging/
microsoft.entityframeworkcore/                           serilog.sinks.file/
microsoft.entityframeworkcore.abstractions/              serilog.sinks.rollingfile/
microsoft.entityframeworkcore.relational/                skywalking.abstractions/
microsoft.extensions.caching.abstractions/               skywalking.agent.aspnetcore/
microsoft.extensions.caching.memory/                     skywalking.core/
microsoft.extensions.configuration/                      skywalking.diagnostics.aspnetcore/
microsoft.extensions.configuration.abstractions/         skywalking.diagnostics.entityframeworkcore/
microsoft.extensions.configuration.binder/               skywalking.diagnostics.entityframeworkcore.npgsql/
microsoft.extensions.configuration.environmentvariables/ skywalking.diagnostics.entityframeworkcore.pomelo.mysql/
microsoft.extensions.configuration.fileextensions/       skywalking.diagnostics.httpclient/
microsoft.extensions.configuration.json/                 skywalking.diagnostics.sqlclient/
microsoft.extensions.dependencyinjection/                skywalking.transport.grpc/
microsoft.extensions.dependencyinjection.abstractions/   skywalking.utilities.configuration/
microsoft.extensions.fileproviders.abstractions/         skywalking.utilities.dependencyinjection/
microsoft.extensions.fileproviders.physical/             skywalking.utilities.logging/
microsoft.extensions.filesystemglobbing/                 system.data.sqlclient/
microsoft.extensions.hosting.abstractions/               system.diagnostics.diagnosticsource/
microsoft.extensions.logging/                            system.interactive.async/
microsoft.extensions.logging.abstractions/               system.runtime.compilerservices.unsafe/
microsoft.extensions.options/                            system.text.encoding.codepages/
microsoft.extensions.primitives/                         system.text.encodings.web/
root@gc:/usr/local/share/dotnet# ls store/x64/netcoreapp2.1/
```
目前在docker中部署项目,skywalkapm仍然处于不可用状态;
在win10下可以正常使用skywalkapm,所以只能在调试阶段使用,发布阶段还没有用起来.
* 希望有比较全的dockerfile部署方案给予参考,或者提供比较友好的skyapm的docker部署体验,非常感谢大佬们的辛勤工作,谢谢!

**Comment by dcdlove** [comment]
直接下载部署包简单

**Comment by jiahengaa** [comment]
> 直接下载部署包简单

能详细点吗,我没找到部署包

**Comment by liuhaoyang** [comment]
这不是skyapm的问题，你需要先搞明白.net core 是怎么查找程序集的.....

**Comment by jiahengaa** [comment]
> 这不是skyapm的问题，你需要先搞明白.net core 是怎么查找程序集的.....

嗯，他说的就是找不到程序集的问题，所以我才说能不能做的友好点😁

**Comment by jiahengaa** [comment]
谢谢大家的回答，目前该问题已解决，
在docker下部署时，需要增加环境变量：
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
尽管这个环境变量在webapi的项目的/Properties/launchSettings.json里定义过，但是在docker环境下不起作用，必须在dockerfile里加上上面那句。

Dockerfile Example：
``` Dockerfile
FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
RUN dotnet tool install -g SkyWalking.DotNet.CLI
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet skywalking install
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /

ENV PATH="$PATH:/usr/local/share/dotnet/store"
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyWalking.Agent.AspNetCore
ENV DOTNET_ADDITIONAL_DEPS=/usr/local/share/dotnet/x64/additionalDeps/skywalking.agent.aspnetcore
ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
COPY --from=build /usr/local/share/dotnet/store /usr/share/dotnet/store
COPY --from=build /usr/local/share/dotnet/x64 /usr/local/share/dotnet/x64

COPY bin/Debug/netcoreapp2.2/publish /app/
WORKDIR /app
ENTRYPOINT ["dotnet", "your-webapi-app.dll"]
```

**Comment by jiahengaa** [comment]
问题已解决

**Comment by liguobao** [comment]
建议把这个方案写到文档啦。
