### ISSUE TITLE
Support Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by chenhw** [SkyAPM/SkyAPM-dotnet#258]
引用System.Data.SqlClient，切换到最新的Microsoft.Data.SqlClient后报错。
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at AspectCore.Extensions.Reflection.MethodReflector.GetDisplayName(MethodInfo method)
   at AspectCore.Extensions.Reflection.MethodReflector..ctor(MethodInfo reflectionInfo)
   at AspectCore.Extensions.Reflection.MethodReflector.<>c__DisplayClass0_0.<Create>g__CreateInternal|0(Pair`2 item)
   at AspectCore.Extensions.Reflection.ReflectorCacheUtils`2.<>c__DisplayClass1_0.<GetOrAdd>b__0(TMemberInfo k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AspectCore.Extensions.Reflection.ReflectorCacheUtils`2.GetOrAdd(TMemberInfo key, Func`2 factory)
   at AspectCore.Extensions.Reflection.MethodReflector.Create(MethodInfo reflectionInfo, CallOptions callOption)
   at AspectCore.Extensions.Reflection.ReflectorExtensions.GetReflector(MethodInfo method, CallOptions callOption)
   at SkyApm.Diagnostics.TracingDiagnosticMethodCollection..ctor(ITracingDiagnosticProcessor tracingDiagnosticProcessor)
   at SkyApm.Diagnostics.TracingDiagnosticObserver..ctor(ITracingDiagnosticProcessor tracingDiagnosticProcessor, ILoggerFactory loggerFactory)
   at SkyApm.Diagnostics.TracingDiagnosticProcessorObserver.Subscribe(DiagnosticListener listener, ITracingDiagnosticProcessor tracingDiagnosticProcessor)
   at SkyApm.Diagnostics.TracingDiagnosticProcessorObserver.OnNext(DiagnosticListener listener)
   at System.Diagnostics.DiagnosticListener.AllListenerObservable.OnNewDiagnosticListener(DiagnosticListener diagnosticListener)
   at System.Diagnostics.DiagnosticListener..ctor(String name)
   at Microsoft.Data.SqlClient.SqlConnection..cctor()

**Comment by liuhaoyang** [comment]
目前还没有做对Microsoft.Data.SqlClient的适配

**Comment by ElderJames** [comment]
It depends on dotnet/SqlClient/issues/93

**Comment by ElderJames** [comment]
You can use `System.Data.SqlClient` first.
