### ISSUE TITLE
skyapm.json 配置文件不生效

### ISSUE THREAD

**Issue by rockzhouj** [SkyAPM/SkyAPM-dotnet#294]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by rockzhouj** [comment]
2020-04-21 17:52:32.652 +08:00 [sample_app] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()

**Comment by snakorse** [comment]
看起来是你配置的skywalking server地址有问题，需要自己检查下skywalking是否能正常访问，再再次确认skyapm.json配置的正确性
