### ISSUE TITLE
unable to register service

### ISSUE THREAD

**Issue by mchenx** [SkyAPM/SkyAPM-dotnet#327]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Maybe this is a bug, maybe not, I don't know. So I raise this as a question.

Does version SkyAPM.Agent.AspNetCore version 0.9.0 supports netcoreapp2.1 web app?

I integrated SkyAPM.Agent.AspNetCore with an webapi project (netcoreapp2.1), no apm data was sent to oap server.
Looking at the log, it seems the grpc client couldn't be registered successfully.

`2020-09-08 15:57:34.286 +08:00 [sw-api-gw-dev] [Information] SkyApm.InstrumentStartup : Started SkyAPM .NET Core Agent.
2020-09-08 15:57:34.431 +08:00 [sw-api-gw-dev] [Information] SkyApm.Transport.Grpc.ConnectionManager : Connected server[dev01.zyx.local:11800].
2020-09-08 15:57:35.061 +08:00 [sw-api-gw-dev] [Error] SkyApm.Transport.Grpc.V6.ServiceRegister : Register service fail.
Grpc.Core.RpcException: Status(StatusCode=Unimplemented, Detail="Method not found: Register/doServiceRegister")
   at SkyApm.Transport.Grpc.V6.ServiceRegister.<>c__DisplayClass9_0.<<RegisterServiceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at SkyApm.Transport.Grpc.Common.Call.Execute[T](Func`1 task, Func`1 errCallback, Func```1 errMessage)
2020-09-08 15:57:35.062 +08:00 [sw-api-gw-dev] [Warning] SkyApm.Transport.Grpc.ConnectionManager : Connection state changed. Connected -> Ready . Status(StatusCode=Unimplemented, Detail="Method not found: Register/doServiceRegister")
2020-09-08 15:57:49.270 +08:00 [sw-api-gw-dev] [Information] SkyApm.Transport.Grpc.ConnectionManager : Shutdown connection[dev01.zyx.local:11800].`

**Comment by mchenx** [comment]
this seems to be duplicated of #311

**Comment by snakorse** [comment]
Seems you are using skywalking 8.x, you should upgrade the skyapm agent version to 1.0 which has support for skywalking 8.x.
