### ISSUE TITLE
Not possible to send data to Elasticsearch - Can't split instance id into 2 parts

### ISSUE THREAD

**Issue by joacatito** [SkyAPM/SkyAPM-dotnet#328]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?
Skywalking 8.1.0, SkyAPM.Agent.AspNetCore 1.0.0, ElasticSearch 7.5.0, Windows 10, .NET Core 3.1

- What happen?

Is not possible to send data to ElasticSearch.

```
2020-09-10 11:44:19,545 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker -388620 [pool-5-thread-1] ERROR [] - Can't split instance id into 2 parts, 665181202db748f0bda32cfe1093bf25

org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, 665181202db748f0bda32cfe1093bf25

at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceInstanceID.analysisId(IDManager.java:121) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.alarm.provider.NotifyHandler.notify(NotifyHandler.java:75) ~[server-alarm-plugin-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.alarm.AlarmEntrance.forward(AlarmEntrance.java:39) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:41) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:30) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.lambda$nextWorker$2(MetricsPersistentWorker.java:199) ~[server-core-8.1.0.jar:8.1.0]

at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212]

at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.nextWorker(MetricsPersistentWorker.java:199) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:188) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:146) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.1.0.jar:8.1.0]

at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]

at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) ~[server-core-8.1.0.jar:8.1.0]

at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.1.0.jar:8.1.0]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]

at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

skyapm.json
```
{
  "SkyWalking": {
    "ServiceName": "my_application",
    "Namespace": "",
    "HeaderVersions": [
      "sw8"
    ],
    "Sampling": {
      "SamplePer3Secs": -1,
      "Percentage": -1.0
    },
    "Logging": {
      "Level": "Information",
      "FilePath": "logs\\skyapm-{Date}.log"
    },
    "Transport": {
      "Interval": 3000,
      "ProtocolVersion": "v8",
      "QueueSize": 30000,
      "BatchSize": 3000,
      "gRPC": {
        "Servers": "localhost:11800",
        "Timeout": 10000,
        "ConnectTimeout": 10000,
        "ReportTimeout": 600000,
        "Authentication": ""
      }
    }
  }
}
```
Environment variables
```
"ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "SkyAPM.Agent.AspNetCore"
"SKYWALKING__SERVICENAME": "my_application"
```

**Comment by snakorse** [comment]
It's a known bug in the skywalking oap server side, this bug only causes the clr thread metrics failed to report, and it has been fixed in [this  pr](https://github.com/apache/skywalking/pull/5345), so you can either waiting for the next skywalking official release or build on your own by downloading the latest source code.

**Comment by wu-sheng** [comment]
@snakorse Thanks for the feedback.
