### ISSUE TITLE
Grpc 调用报错，上下文中stack值为null，导致后面提交数据的时候报错

### ISSUE THREAD

**Issue by LuceLuo** [SkyAPM/SkyAPM-dotnet#338]
2020-10-29 12:01:32.794 +08:00 [NN.Platform] [Error] SkyApm.Transport.Grpc.V8.SegmentReporter : Report trace segment fail.
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at SkyWalking.NetworkProtocol.V3.KeyStringValuePair.set_Value(String value)
   at SkyApm.Transport.Grpc.Common.SegmentV8Helpers.<>c.<MapToLogMessage>b__3_0(KeyValuePair`2 x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at SkyApm.Transport.Grpc.Common.SegmentV8Helpers.MapToLogMessage(LogDataRequest request)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at SkyApm.Transport.Grpc.Common.SegmentV8Helpers.MapToSpan(SpanRequest request)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at SkyApm.Transport.Grpc.Common.SegmentV8Helpers.Map(SegmentRequest request)
   at SkyApm.Transport.Grpc.V8.SegmentReporter.ReportAsync(IReadOnlyCollection`1 segmentRequests, CancellationToken cancellationToken)
2020-10-29 12:01:32.794 +08:00 [NN.Platform] [Warning] SkyApm.Transport.Grpc.ConnectionManager : Connection state changed. Connected -> Ready . Value cannot be null. (Parameter 'value')

![QQ截图20201029124128](https://user-images.githubusercontent.com/8308243/97526484-36f20280-19e4-11eb-96b3-5ce75eeaa982.png)

**Comment by LuceLuo** [comment]
![image](https://user-images.githubusercontent.com/8308243/97529090-217fd700-19ea-11eb-8d1f-3c90a8a3f093.png)
跟踪到是这里填入的null值

**Comment by snakorse** [comment]
@LuceLuo  Thanks for your feedback, this is a bug, null values should be skiped. Would you like to fix it and make a pull request?
