### ISSUE TITLE
[Error] Error loading native library  "D:\xxxxx\runtimes/win/native\grpc_csharp_ext.x64.dll"

### ISSUE THREAD

**Issue by GavinHome** [SkyAPM/SkyAPM-dotnet#379]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Bug
___

### Bug
- Which version of SkyWalking, OS and .NET Runtime?
SkyWalking: SkyAPM.Agent.AspNetCore 1.1.0
OS: Window Server 2012  X64
.NET: dotnet core 3.1
IIS: 8.5.9600.16384

- What happen?
2021-01-27 10:54:31.306 +08:00 [Error] SkyApm.Transport.Grpc.ConnectService : SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(token.Token) fail
System.IO.IOException: Error loading native library "D:\xxxxxxx\runtimes/win/native\grpc_csharp_ext.x64.dll". 
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
   at SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(CancellationToken cancellationToken)
   at SkyApm.ExecutionService.Callback(Object state)

**Comment by GavinHome** [comment]
Well, I solved it through this [issue](https://github.com/grpc/grpc/issues/21550):

1. open url: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
2. download vc_redist.x64.exe, and install.
   
![image](https://user-images.githubusercontent.com/5460850/105953191-b6f43b00-60ad-11eb-8179-00ab706b89a5.png)


It works well....

**Comment by zeaposs** [comment]
Reopening the issue - thanks for the report and additional info about the bug. This can be fixed on our side by updating [grpc](https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/src/SkyApm.Transport.Grpc.Protocol/SkyApm.Transport.Grpc.Protocol.csproj#L19-L20) to a newer version, 2.27 at least.

**Comment by Sky-shang** [comment]
Install the latest GRPC package independently

**Comment by Sky-shang** [comment]
Install the latest GRPC package independently to solve this problem.
