### ISSUE TITLE
ocelot项目使用SkyAPM.Agent.AspNetCore导致下级服务(.net core)集成的SkyAPM.Agent.AspNetCore不能正常解析数据

### ISSUE THREAD

**Issue by sjdboy** [SkyAPM/SkyAPM-dotnet#404]
情况如下：

- 网站项目均为.net 5，使用的 SkyAPM.Agent.AspNetCore 版本是1.2.0 ，ocelot版本是17.0.0

- 请求过程为

> 网站A->ocelot->服务B

- 服务B中skyapm错误日志(skyapm-20210406.log)如下：

> 2021-04-06 16:16:29.964 +08:00 [WangHongUserService] [Error] SkyApm.Diagnostics.TracingDiagnosticObserver : Invoke diagnostic method exception.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at SkyApm.Base64Formatter.Decode(String value)
   at SkyApm.Tracing.Sw8CarrierFormatter.Decode(String content)
   at SkyApm.Tracing.CarrierPropagator.Extract(ICarrierHeaderCollection headerCollection)
   at SkyApm.Tracing.TracingContext.CreateEntrySegmentContext(String operationName, ICarrierHeaderCollection carrierHeader)
   at SkyApm.Diagnostics.AspNetCore.Handlers.DefaultHostingDiagnosticHandler.BeginRequest(ITracingContext tracingContext, HttpContext httpContext)
   at SkyApm.AspNetCore.Diagnostics.HostingTracingDiagnosticProcessor.BeginRequest(HttpContext HttpContext)
   at invoker_Void BeginRequest(HttpContext)(Object , Object[] )
   at AspectCore.Extensions.Reflection.MethodReflector.Invoke(Object instance, Object[] parameters)
   at SkyApm.Diagnostics.TracingDiagnosticMethod.Invoke(String diagnosticName, Object value)
   at SkyApm.Diagnostics.TracingDiagnosticObserver.OnNext(KeyValuePair`2 value)

- 使用fiddler获取信息如下

1. 获取到网站A请求ocelot带的http头sw8值为：

> 1-ZTExYWM1YTY0Zjc4MmMyY2RmMzBkYzlhY2U0OThhZjkuNTEuMTYxNzY5MTE1NzgxOTAwMzA=-ZTExYWM1YTY0Zjc4MmMyY2RmMzBkYzlhY2U0OThhZjkuNDcuMTYxNzY5MTE2NDQwODAwMjE=-0-V2FuZ0hvbmdCcmluZ1dlYkFwcA==-MTkyLjE2OC4wLjNAMDU1ZmFlZjc5OTFjNDQ4OGEzODVmMTEwMmRmMTA0YWQ=-aHR0cDovLzE5Mi4xNjguMC4zOjg1L2NvbW1hbmQvV2FuZ0hvbmdCcmluZy5Db21tYW5kcy5USy5BZGRHb29kc0NvbW1hbmQ=-MTkyLjE2OC4wLjM6ODU=

1. 获取到ocelot请求服务B带的http头 sw8值为：

> 1-ZTExYWM1YTY0Zjc4MmMyY2RmMzBkYzlhY2U0OThhZjkuNTEuMTYxNzY5MTE1NzgxOTAwMzA=-ZTExYWM1YTY0Zjc4MmMyY2RmMzBkYzlhY2U0OThhZjkuNDcuMTYxNzY5MTE2NDQwODAwMjE=-0-V2FuZ0hvbmdCcmluZ1dlYkFwcA==-MTkyLjE2OC4wLjNAMDU1ZmFlZjc5OTFjNDQ4OGEzODVmMTEwMmRmMTA0YWQ=-aHR0cDovLzE5Mi4xNjguMC4zOjg1L2NvbW1hbmQvV2FuZ0hvbmdCcmluZy5Db21tYW5kcy5USy5BZGRHb29kc0NvbW1hbmQ=-MTkyLjE2OC4wLjM6ODU=, 1-ZTExYWM1YTY0Zjc4MmMyY2RmMzBkYzlhY2U0OThhZjkuNTEuMTYxNzY5MTE1NzgxOTAwMzA=-MjlhNzhjNTkyM2NhNTI5MTM4YmMxMDBiMDFmMjE0NTguNDYuMTYxNzY5MTE2NDQxNTAwNjg=-0-V2FuZ0hvbmdHYXRld2F5-MTkyLjE2OC4wLjNAZmFhMjlmMDA2YzNmNDNlNGFmOTUzNmE1MjBlNzdjOTA=-aHR0cDovLzE5Mi4xNjguMC4zOjUwOTU2L2FwaS9jb21tYW5k-MTkyLjE2OC4wLjM6NTA5NTY=
 **这段内容包括了两段值，以逗号分隔。**

`
判断sw8内容（以逗号分隔）是错误的导致服务B中 skyapm异常。是不是我哪里配置不对，还是类库有问题？

**Comment by snakorse** [comment]
It's a known bug, have been fixed by #384 . You can reference the 1.3.0-prerelease-xxx version from Myget source to fix this.

**Comment by sjdboy** [comment]
> It's a known bug, have been fixed by #384 . You can reference the 1.3.0-prerelease-xxx version from Myget source to fix this.
thank you
