### ISSUE TITLE
Unable to load shared library 'libdl.so' or one of its dependencies.

### ISSUE THREAD

**Issue by sjdboy** [SkyAPM/SkyAPM-dotnet#405]
### 问题
- 在docker中运行出错，skyapm日志：
2021-04-08 20:45:38.442 +08:00 [WangHongIdentityServer] [Error] SkyApm.Transport.Grpc.ConnectService : SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(token.Token) fail
System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
   at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
   at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
   at SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(CancellationToken cancellationToken)
   at SkyApm.ExecutionService.Callback(Object state)
2021-04-08 20:45:53.441 +08:00 [WangHongIdentityServer] [Error] SkyApm.Transport.Grpc.ConnectService : SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(token.Token) fail
System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
   at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
   at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
   at SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(CancellationToken cancellationToken)
   at SkyApm.ExecutionService.Callback(Object state)
2021-04-08 20:46:08.442 +08:00 [WangHongIdentityServer] [Error] SkyApm.Transport.Grpc.ConnectService : SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(token.Token) fail
System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
   at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
   at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
   at SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(CancellationToken cancellationToken)
   at SkyApm.ExecutionService.Callback(Object state)

___
- 相关组件及系统版本信息
SkyAPM.Agent.AspNetCore 1.2.0
Docker version 20.10.5
mcr.microsoft.com/dotnet/aspnet:5.0

**Comment by snakorse** [comment]
Some external lib needed for the dotnet 5.0 docker image, try add these lines to your Dockerfile should work.

```docker
RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list && \
    sed -i "s@http://security.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list && \
    apt-get update
RUN apt-get install -y --allow-unauthenticated \
    apt-utils libgdiplus nano libc6-dev libx11-dev && \
    ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll
RUN apt-get install -y --allow-unauthenticated procps
```

**Comment by snakorse** [comment]
You can also solve this by updating gRpc to 2.34.0, see [here ](https://github.com/grpc/grpc/issues/24153).
