### ISSUE TITLE
skywalking oap server how to connection  es7 with https (with self-signed certificate)  ?

### ISSUE THREAD

**Issue by sjdboy** [SkyAPM/SkyAPM-dotnet#436]
es7 address: 
https://192.168.3.49:9200 

skywalking error log:
2021-08-11 17:33:24,942 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -4982 [main] INFO  [] - start the provider default in alarm module.
2021-08-11 17:33:24,943 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -4983 [main] INFO  [] - start the provider default in event-analyzer module.
2021-08-11 17:33:24,988 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager -5028 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.source.oal.rt.dispatcher.EventDispatcher is added into DefaultScopeDefine 43.
2021-08-11 17:33:24,992 - org.apache.skywalking.oap.server.library.module.BootstrapFlow -5032 [main] INFO  [] - start the provider elasticsearch7 in storage module.
2021-08-11 17:33:24,993 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -5033 [main] INFO  [] - elasticsearch cluster nodes: 192.168.3.49:9200
2021-08-11 17:33:25,824 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -5864 [main] ERROR [] - Connection is closed
org.apache.skywalking.oap.server.library.module.ModuleStartException: Connection is closed
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:228) ~[storage-elasticsearch7-plugin-8.7.0.jar:8.7.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:49) ~[library-module-8.7.0.jar:8.7.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-8.7.0.jar:8.7.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-8.7.0.jar:8.7.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-8.7.0.jar:8.7.0]
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:869) ~[elasticsearch-rest-client-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283) ~[elasticsearch-rest-client-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[elasticsearch-rest-client-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1617) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:775) ~[elasticsearch-rest-high-level-client-7.10.2.jar:7.10.2]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.connect(ElasticSearch7Client.java:111) ~[storage-elasticsearch7-plugin-8.7.0.jar:8.7.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:223) ~[storage-elasticsearch7-plugin-8.7.0.jar:8.7.0]
	... 4 more
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]

**Comment by wu-sheng** [comment]
We have provided document.
