### ISSUE TITLE
The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception.

### ISSUE THREAD

**Issue by pccai** [SkyAPM/SkyAPM-dotnet#450]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- 1.3.0

Sometimes exception on net5.0.400:

[Error] SkyApm.Transport.Grpc.ConnectService : SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(token.Token) fail
System.TypeInitializationException: The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception.
 ---> System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
ader is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
   at Grpc.Core.Internal.PlatformApis.<>c.<TryGetUnityApplicationPlatform>b__43_0(Assembly assembly)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Grpc.Core.Internal.PlatformApis.TryGetUnityApplicationPlatform()
   at Grpc.Core.Internal.PlatformApis..cctor()
   --- End of inner exception stack trace ---
   at Grpc.Core.Internal.PlatformApis.get_IsXamarinIOS()
   at Grpc.Core.GrpcEnvironment.get_IsNativeShutdownAllowed()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
   at SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(CancellationToken cancellationToken)
   at SkyApm.ExecutionService.Callback(Object state)

**Comment by feiyun0112** [comment]
`ader is an invalid culture identifier.`

@pccai 

did you change current culture?
