### ISSUE TITLE
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by pccai** [SkyAPM/SkyAPM-dotnet#452]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ * ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at System.Reflection.RuntimeAssembly.GetSimpleName(System.Runtime.CompilerServices.QCallAssembly, System.Runtime.CompilerServices.StringHandleOnStack)
--------------------------------
   at System.Reflection.RuntimeAssembly.GetSimpleName()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at Grpc.Core.Internal.PlatformApis+<>c.<TryGetUnityApplicationPlatform>b__43_0(System.Reflection.Assembly)
   at System.Linq.Enumerable.TryGetFirst[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>, Boolean ByRef)
   at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at Grpc.Core.Internal.PlatformApis.TryGetUnityApplicationPlatform()
   at Grpc.Core.Internal.PlatformApis..cctor()
   at Grpc.Core.Internal.PlatformApis.get_IsXamarinIOS()
   at Grpc.Core.GrpcEnvironment.get_IsNativeShutdownAllowed()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(System.String, Grpc.Core.ChannelCredentials, System.Collections.Generic.IEnumerable`1<Grpc.Core.ChannelOption>)
   at Grpc.Core.Channel..ctor(System.String, Grpc.Core.ChannelCredentials)
   at SkyApm.Transport.Grpc.ConnectionManager+<ConnectAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[SkyApm.Transport.Grpc.ConnectionManager+<ConnectAsync>d__10, SkyAPM.Transport.Grpc, Version=1.3.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01]](<ConnectAsync>d__10 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[SkyApm.Transport.Grpc.ConnectionManager+<ConnectAsync>d__10, SkyAPM.Transport.Grpc, Version=1.3.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01]](<ConnectAsync>d__10 ByRef)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
   at SkyApm.Transport.Grpc.ConnectService+<ExecuteAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[SkyApm.Transport.Grpc.ConnectService+<ExecuteAsync>d__8, SkyAPM.Transport.Grpc, Version=1.3.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01]](<ExecuteAsync>d__8 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[SkyApm.Transport.Grpc.ConnectService+<ExecuteAsync>d__8, SkyAPM.Transport.Grpc, Version=1.3.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01]](<ExecuteAsync>d__8 ByRef)
   at SkyApm.Transport.Grpc.ConnectService.ExecuteAsync(System.Threading.CancellationToken)
   at SkyApm.ExecutionService+<Callback>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[SkyApm.ExecutionService+<Callback>d__8, SkyAPM.Abstractions, Version=1.3.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01]](<Callback>d__8 ByRef)
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[SkyApm.ExecutionService+<Callback>d__8, SkyAPM.Abstractions, Version=1.3.0.0, Culture=neutral, PublicKeyToken=186054a41664fe01]](<Callback>d__8 ByRef)
   at SkyApm.ExecutionService.Callback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by feiyun0112** [comment]
@pccai 

can you attach a minimal reproduction demo application?
