### ISSUE TITLE
SkyApm Log  exception

### ISSUE THREAD

**Issue by sampsonye** [SkyAPM/SkyAPM-dotnet#505]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and .NET Runtime?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
```
Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SkyApm.Transport.SegmentContextMapper.Map(SegmentContext segmentContext)
   at SkyApm.Transport.LoggerContextContextMapper.Map(LoggerContext loggerContext)
   at SkyApm.Transport.AsyncQueueSkyApmLogDispatcher.Dispatch(LoggerContext loggerContext)
   at SkyApm.Diagnostics.MSLogging.SkyApmLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at DotNetCore.CAP.Processor.CapProcessingServer.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|16_0(Object o)
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
```
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by GeorGeWzw** [comment]
In what scenario does this error occur? @sampsonye

**Comment by sampsonye** [comment]
> In what scenario does this error occur? @sampsonye

Use Cap

**Comment by GeorGeWzw** [comment]
I want to know whether the problem occurs when Cap produces messages or when Cap consumes messages? @sampsonye

**Comment by sampsonye** [comment]
> I want to know whether the problem occurs when Cap produces messages or when Cap consumes messages? @sampsonye

i say  just in cap Bootstrap ,you can find it on exception stack 

the really code just:
![image](https://user-images.githubusercontent.com/5895634/190162628-10425d58-f842-4e35-90b6-7c8f96d8139f.png)

and you can make a test just do not have any  EntrySegment


finally can we close this log? it is redundant, for us

**Comment by liuhaoyang** [comment]
> > I want to know whether the problem occurs when Cap produces messages or when Cap consumes messages? @sampsonye
> 
> i say just in cap Bootstrap ,you can find it on exception stack
> 
> the really code just: ![image](https://user-images.githubusercontent.com/5895634/190162628-10425d58-f842-4e35-90b6-7c8f96d8139f.png)
> 
> and you can make a test just do not have any EntrySegment
> 
> finally can we close this log? it is redundant for us

@GeorGeWzw I think it's reasonable to allow users to disable logging integration.

**Comment by sampsonye** [comment]
it seem like a critical fault
it make logger broken when we do not have init EntrySegment
Just happen Like:
1. some module that do not use skyapm.like quartz,hangfire and so on
2. BackgroundService、HostService

@liuhaoyang @GeorGeWzw  any suggestions?

**Comment by liuhaoyang** [comment]
> it seem like a critical fault it make logger broken when we do not have init EntrySegment Just happen Like:
> 
> 1. some module that do not use skyapm like quartz,hangfire and so on
> 2. BackgroundService、HostService
> 
> @liuhaoyang @GeorGeWzw any suggestions?

 I just re-reviewed the code [LoggerContextContextMapper.cs#L34](https://github.com/SkyAPM/SkyAPM-dotnet/blob/main/src/SkyApm.Core/Transport/LoggerContextContextMapper.cs#L34) should check if SegmentContext is null before mapping SegmentContext to segmentRequest
